gradle loadVotes -PparseFile=votes/xaa.xml &
gradle loadVotes -PparseFile=votes/xab.xml &
gradle loadVotes -PparseFile=votes/xac.xml &
gradle loadVotes -PparseFile=votes/xad.xml &
gradle loadVotes -PparseFile=votes/xae.xml &
gradle loadVotes -PparseFile=votes/xaf.xml &
gradle loadVotes -PparseFile=votes/xag.xml &
gradle loadVotes -PparseFile=votes/xah.xml &
gradle loadVotes -PparseFile=votes/xai.xml &
gradle loadVotes -PparseFile=votes/xaj.xml 
gradle loadVotes -PparseFile=votes/xak.xml &
gradle loadVotes -PparseFile=votes/xal.xml &
gradle loadVotes -PparseFile=votes/xam.xml &
gradle loadVotes -PparseFile=votes/xan.xml &
gradle loadVotes -PparseFile=votes/xao.xml &
gradle loadVotes -PparseFile=votes/xap.xml &
gradle loadVotes -PparseFile=votes/xaq.xml &
gradle loadVotes -PparseFile=votes/xar.xml &
gradle loadVotes -PparseFile=votes/xas.xml &
gradle loadVotes -PparseFile=votes/xat.xml 
gradle loadVotes -PparseFile=votes/xau.xml &
gradle loadVotes -PparseFile=votes/xav.xml &
gradle loadVotes -PparseFile=votes/xaw.xml &
gradle loadVotes -PparseFile=votes/xax.xml &
gradle loadVotes -PparseFile=votes/xay.xml &
gradle loadVotes -PparseFile=votes/xaz.xml &
gradle loadVotes -PparseFile=votes/xba.xml &
gradle loadVotes -PparseFile=votes/xbb.xml &
gradle loadVotes -PparseFile=votes/xbc.xml &
gradle loadVotes -PparseFile=votes/xbd.xml &
gradle loadVotes -PparseFile=votes/xbe.xml 
